DROP TABLE STUDENT;
DROP TABLE COURSES;
CREATE TABLE STUDENT(ID   INT NOT NULL, NAME VARCHAR(20) NOT NULL, COURSE  VARCHAR(20) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE COURSES(COURSE VARCHAR(20));


INSERT INTO COURSES (COURSE) VALUES ("JAVA");
INSERT INTO COURSES (COURSE) VALUES ("DOT NET");
INSERT INTO COURSES (COURSE) VALUES ("SQL");
INSERT INTO COURSES (COURSE) VALUES ("LINUX");
INSERT INTO COURSES (COURSE) VALUES ("SAS");
INSERT INTO COURSES (COURSE) VALUES ("MAIN FRAMES");


